version: '3'
services:
  uvirtual:
    image: moodle
    volumes:
      - ${MOODLE_FOLDER}:/var/www/html/moodle
      - ${MOODLEDATA_FOLDER}:/var/www/html/moodledata
      - ${MOODLE_LOG_FOLDER}:/var/log/httpd
      - ./.env:/home/.env
    command: bash /home/start.sh
    ports:
      - ${MOODLE_NETWORK}:${MOODLE_PORT}:80
  
  vpl:
    image: vpljailtest
    cap_add: ["SYS_ADMIN"]
    volumes:
      - ${VPL_LOG_FOLDER}:/etc/vpl
    ports: 
      - ${VPL_NETWORK}:${VPL_PORT}:80
    



